- id: apply-copyright-notice
  name: Apply the copywright notice
  description: This hook applies the copyright notice and license disclaimer to all files.
  entry: tools/check_copyright_and_license_disclaimers.py --fix-in-place
  language: python
  types:
    - markdown
    - python
